import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./ui/navbar";
import { FooterPage } from "./ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YinDyeArt - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
